//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmpTasks = new HashSet<EmpTask>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public long Salary { get; set; }
    
        public virtual ICollection<EmpTask> EmpTasks { get; set; }
    }
}
